"""Safe session-scoped filesystem storage."""

from __future__ import annotations

import shutil
import re
import zipfile
from pathlib import Path, PurePosixPath

from fastapi import UploadFile

from backend.app.core.config import (
    MAX_ARCHIVE_MEMBER_BYTES,
    MAX_EDF_FILES_PER_ARCHIVE,
    MAX_UPLOAD_BYTES,
    SESSION_STORAGE_DIR,
)


class StorageError(ValueError):
    """Raised when an archive or storage operation is unsafe."""


class SessionStorage:
    """Manage private files for opaque analysis sessions.

    The class owns the directory layout but never exposes private paths in
    API responses. Original uploads remain separate from derived artifacts.
    """

    def __init__(self, root: Path = SESSION_STORAGE_DIR) -> None:
        """Configure storage beneath a session-root directory.

        Parameters
        ----------
        root : pathlib.Path
            Parent directory for all session files.
        """

        self.root = root

    def session_dir(self, session_id: str) -> Path:
        """Create and return the private root for one session.

        Parameters
        ----------
        session_id : str
            Opaque session identifier generated by the application.

        Returns
        -------
        pathlib.Path
            Session directory path for internal service use.
        """

        path = self.root / session_id
        path.mkdir(parents=True, exist_ok=True)
        return path

    def directory(self, session_id: str, name: str) -> Path:
        """Create and return one approved artifact directory.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        name : str
            One of ``original``, ``extracted``, ``deidentified``,
            ``processed``, or ``explanations``.

        Returns
        -------
        pathlib.Path
            Private directory for the requested artifact category.

        Raises
        ------
        StorageError
            Raised for unknown artifact categories.
        """

        if name not in {"original", "extracted", "deidentified", "processed", "explanations"}:
            raise StorageError("Unknown session storage area.")
        path = self.session_dir(session_id) / name
        path.mkdir(parents=True, exist_ok=True)
        return path

    async def save_upload(self, session_id: str, upload: UploadFile) -> Path:
        """Stream an uploaded ZIP to private original-file storage.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        upload : fastapi.UploadFile
            Multipart upload supplied by FastAPI.

        Returns
        -------
        pathlib.Path
            Internal path to the stored archive.

        Raises
        ------
        StorageError
            Raised for missing filenames or oversized uploads.
        """

        if not upload.filename:
            raise StorageError("Uploaded archive has no filename.")
        destination = self.directory(session_id, "original") / "upload.zip"
        total = 0
        with destination.open("wb") as output:
            while chunk := await upload.read(1024 * 1024):
                total += len(chunk)
                if total > MAX_UPLOAD_BYTES:
                    destination.unlink(missing_ok=True)
                    raise StorageError("Uploaded archive exceeds the size limit.")
                output.write(chunk)
        return destination

    @staticmethod
    def _safe_member_path(member_name: str) -> PurePosixPath:
        """Validate one ZIP member path against traversal attacks.

        Parameters
        ----------
        member_name : str
            Path supplied by the ZIP archive.

        Returns
        -------
        pathlib.PurePosixPath
            Normalized safe archive-relative path.

        Raises
        ------
        StorageError
            Raised for absolute paths, parent traversal, or invalid names.
        """

        member_name = member_name.replace("\\", "/")
        candidate = PurePosixPath(member_name)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise StorageError("Archive contains an unsafe path.")
        if not candidate.name:
            raise StorageError("Archive contains an invalid file path.")
        return candidate

    def extract_edfs(self, session_id: str, archive_path: Path) -> list[Path]:
        """Extract validated EDF members into the session directory.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        archive_path : pathlib.Path
            Private ZIP archive path.

        Returns
        -------
        list[pathlib.Path]
            Extracted EDF paths in natural filename order.

        Raises
        ------
        StorageError
            Raised for missing EDF files, unsafe paths, duplicate basenames,
            oversized members, or too many recordings.
        """

        extracted_dir = self.directory(session_id, "extracted")
        with zipfile.ZipFile(archive_path) as archive:
            members = [
                member
                for member in archive.infolist()
                if not member.is_dir() and Path(member.filename).suffix.lower() == ".edf"
            ]
            if not members:
                raise StorageError("ZIP archive does not contain EDF files.")
            if len(members) > MAX_EDF_FILES_PER_ARCHIVE:
                raise StorageError("ZIP archive contains too many EDF files.")

            outputs: list[Path] = []
            used_names: set[str] = set()
            natural_key = lambda item: [
                int(part) if part.isdigit() else part.lower()
                for part in re.split(r"(\d+)", item.filename)
            ]
            for member in sorted(members, key=natural_key):
                relative = self._safe_member_path(member.filename)
                if member.file_size > MAX_ARCHIVE_MEMBER_BYTES:
                    raise StorageError("Archive member exceeds the size limit.")
                # Store only the basename to prevent user-controlled directory
                # layouts from escaping the session boundary.
                destination = extracted_dir / relative.name
                if destination.name in used_names:
                    raise StorageError("Archive contains duplicate EDF filenames.")
                used_names.add(destination.name)
                with archive.open(member) as source, destination.open("wb") as output:
                    shutil.copyfileobj(source, output)
                outputs.append(destination)
            return outputs

    def deidentified_path(self, session_id: str, record_id: str) -> Path:
        """Return the private destination for a de-identified EDF.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        record_id : str
            Opaque recording identifier.

        Returns
        -------
        pathlib.Path
            Internal de-identified EDF path.
        """

        return self.directory(session_id, "deidentified") / f"{record_id}.edf"

    def processed_path(self, session_id: str, record_id: str) -> Path:
        """Return the private destination for a processed NPZ artifact.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        record_id : str
            Opaque recording identifier.

        Returns
        -------
        pathlib.Path
            Internal processed-artifact path.
        """

        return self.directory(session_id, "processed") / f"{record_id}.npz"

    def explanation_path(self, session_id: str, prediction_id: int) -> Path:
        """Return the private destination for one explanation JSON file.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        prediction_id : int
            Internal prediction primary key.

        Returns
        -------
        pathlib.Path
            Internal explanation-artifact path.
        """

        return self.directory(session_id, "explanations") / f"prediction-{prediction_id}.json"
