"""Safe session-scoped filesystem storage."""

from __future__ import annotations

import shutil
import re
import os
import secrets
import zipfile
from pathlib import Path, PurePosixPath

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from fastapi import UploadFile

from backend.app.core.config import (
    MAX_ARCHIVE_MEMBER_BYTES,
    MAX_EDF_FILES_PER_ARCHIVE,
    MAX_UPLOAD_BYTES,
    SESSION_STORAGE_DIR,
    STORAGE_KEY_ENV,
)
from backend.app.privacy.crypto import CryptoError, read_base64_key
from backend.app.research.chb_mit import sidecar_annotations, summary_annotations


class StorageError(ValueError):
    """Raised when an archive or storage operation is unsafe."""


_ENCRYPTED_MAGIC = b"MDS01GCM1"
_NONCE_BYTES = 12
_TAG_BYTES = 16
_MAX_ANNOTATION_MEMBER_BYTES = 1024 * 1024


class SessionStorage:
    """Manage private files for opaque analysis sessions.

    The class owns the directory layout but never exposes private paths in
    API responses. All original and derived artifacts are transient by default.
    """

    def __init__(self, root: Path = SESSION_STORAGE_DIR, storage_key: bytes | None = None) -> None:
        """Configure storage beneath a session-root directory.

        Parameters
        ----------
        root : pathlib.Path
            Parent directory for all session files.
        """

        self.root = root
        self.storage_key = storage_key

    def session_dir(self, session_id: str) -> Path:
        """Create and return the private root for one session.

        Parameters
        ----------
        session_id : str
            Opaque session identifier generated by the application.

        Returns
        -------
        pathlib.Path
            Session directory path for internal service use.
        """

        path = self.root / session_id
        path.mkdir(parents=True, exist_ok=True)
        return path

    def directory(self, session_id: str, name: str) -> Path:
        """Create and return one approved artifact directory.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        name : str
            One of ``original``, ``work``, ``extracted``, ``deidentified``,
            ``processed``, or ``explanations``.

        Returns
        -------
        pathlib.Path
            Private directory for the requested artifact category.

        Raises
        ------
        StorageError
            Raised for unknown artifact categories.
        """

        if name not in {"original", "work", "extracted", "deidentified", "processed", "explanations"}:
            raise StorageError("Unknown session storage area.")
        path = self.session_dir(session_id) / name
        path.mkdir(parents=True, exist_ok=True)
        return path

    async def save_upload(self, session_id: str, upload: UploadFile) -> Path:
        """Stream an uploaded ZIP to private original-file storage.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        upload : fastapi.UploadFile
            Multipart upload supplied by FastAPI.

        Returns
        -------
        pathlib.Path
            Internal path to the stored archive.

        Raises
        ------
        StorageError
            Raised for missing filenames or oversized uploads.
        """

        if not upload.filename:
            raise StorageError("Uploaded archive has no filename.")
        destination = self.directory(session_id, "original") / "upload.zip.enc"
        total = 0
        nonce = secrets.token_bytes(_NONCE_BYTES)
        encryptor = Cipher(algorithms.AES(self._key()), modes.GCM(nonce)).encryptor()
        with destination.open("wb") as output:
            output.write(_ENCRYPTED_MAGIC)
            output.write(nonce)
            while chunk := await upload.read(1024 * 1024):
                total += len(chunk)
                if total > MAX_UPLOAD_BYTES:
                    destination.unlink(missing_ok=True)
                    raise StorageError("Uploaded archive exceeds the size limit.")
                output.write(encryptor.update(chunk))
            output.write(encryptor.finalize())
            output.write(encryptor.tag)
        os.chmod(destination, 0o600)
        return destination

    def _key(self) -> bytes:
        """Return the injected test key or the required runtime storage key."""

        try:
            return self.storage_key or read_base64_key(STORAGE_KEY_ENV)
        except CryptoError as exc:
            raise StorageError(str(exc)) from exc

    def materialize_archive(self, session_id: str, encrypted_path: Path) -> Path:
        """Decrypt one private ZIP into a short-lived, owner-only work path."""

        destination = self.directory(session_id, "work") / "upload.zip"
        try:
            size = encrypted_path.stat().st_size
            minimum_size = len(_ENCRYPTED_MAGIC) + _NONCE_BYTES + _TAG_BYTES
            if size < minimum_size:
                raise StorageError("Stored archive is incomplete.")
            with encrypted_path.open("rb") as source:
                if source.read(len(_ENCRYPTED_MAGIC)) != _ENCRYPTED_MAGIC:
                    raise StorageError("Stored archive is not encrypted.")
                nonce = source.read(_NONCE_BYTES)
                source.seek(size - _TAG_BYTES)
                tag = source.read(_TAG_BYTES)
                source.seek(len(_ENCRYPTED_MAGIC) + _NONCE_BYTES)
                remaining = size - len(_ENCRYPTED_MAGIC) - _NONCE_BYTES - _TAG_BYTES
                decryptor = Cipher(algorithms.AES(self._key()), modes.GCM(nonce, tag)).decryptor()
                with destination.open("wb") as output:
                    while remaining:
                        chunk = source.read(min(1024 * 1024, remaining))
                        if not chunk:
                            raise StorageError("Stored archive is incomplete.")
                        remaining -= len(chunk)
                        output.write(decryptor.update(chunk))
                    output.write(decryptor.finalize())
            os.chmod(destination, 0o600)
            return destination
        except StorageError:
            destination.unlink(missing_ok=True)
            raise
        except Exception as exc:
            destination.unlink(missing_ok=True)
            raise StorageError("Stored archive cannot be decrypted.") from exc

    @staticmethod
    def _safe_member_path(member_name: str) -> PurePosixPath:
        """Validate one ZIP member path against traversal attacks.

        Parameters
        ----------
        member_name : str
            Path supplied by the ZIP archive.

        Returns
        -------
        pathlib.PurePosixPath
            Normalized safe archive-relative path.

        Raises
        ------
        StorageError
            Raised for absolute paths, parent traversal, or invalid names.
        """

        member_name = member_name.replace("\\", "/")
        candidate = PurePosixPath(member_name)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise StorageError("Archive contains an unsafe path.")
        if not candidate.name:
            raise StorageError("Archive contains an invalid file path.")
        return candidate

    @staticmethod
    def _is_hidden_member(path: PurePosixPath) -> bool:
        """Return whether a ZIP member is hidden operating-system metadata."""

        return any(part == "__MACOSX" or part.startswith(".") for part in path.parts)

    def read_reference_annotations(self, archive_path: Path) -> dict[str, tuple[str, list[tuple[float, float]]]]:
        """Read optional CHB-MIT reference intervals without retaining source names."""

        annotations: dict[str, tuple[str, list[tuple[float, float]]]] = {}
        summaries: dict[str, list[tuple[float, float]]] = {}
        sidecars: dict[str, list[tuple[float, float]]] = {}
        with zipfile.ZipFile(archive_path) as archive:
            for member in archive.infolist():
                if member.is_dir():
                    continue
                relative = self._safe_member_path(member.filename)
                if self._is_hidden_member(relative) or member.file_size > _MAX_ANNOTATION_MEMBER_BYTES:
                    continue
                lower_name = relative.name.lower()
                try:
                    if lower_name.endswith("-summary.txt"):
                        text = archive.read(member).decode("utf-8-sig")
                        summaries.update(summary_annotations(text))
                    elif lower_name.endswith(".edf.seizures"):
                        edf_name = lower_name.removesuffix(".seizures")
                        sidecars[edf_name] = sidecar_annotations(archive.read(member))
                except (UnicodeDecodeError, ValueError):
                    continue

        for filename, intervals in sidecars.items():
            annotations[filename] = ("chb-mit-sidecar", intervals)
        for filename, intervals in summaries.items():
            annotations[filename] = ("chb-mit-summary", intervals)
        return annotations

    def extract_edfs(self, session_id: str, archive_path: Path) -> list[Path]:
        """Extract validated EDF members into the session directory.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        archive_path : pathlib.Path
            Private ZIP archive path.

        Returns
        -------
        list[pathlib.Path]
            Extracted EDF paths in natural filename order.

        Raises
        ------
        StorageError
            Raised for missing EDF files, unsafe paths, duplicate basenames,
            oversized members, or too many recordings.
        """

        extracted_dir = self.directory(session_id, "extracted")
        with zipfile.ZipFile(archive_path) as archive:
            members: list[tuple[zipfile.ZipInfo, PurePosixPath]] = []
            for member in archive.infolist():
                if member.is_dir():
                    continue
                relative = self._safe_member_path(member.filename)
                if self._is_hidden_member(relative) or relative.suffix.lower() != ".edf":
                    continue
                members.append((member, relative))
            if not members:
                raise StorageError("ZIP archive does not contain EDF files.")
            if len(members) > MAX_EDF_FILES_PER_ARCHIVE:
                raise StorageError("ZIP archive contains too many EDF files.")

            outputs: list[Path] = []
            used_names: set[str] = set()
            natural_key = lambda item: [
                int(part) if part.isdigit() else part.lower()
                for part in re.split(r"(\d+)", item[1].name)
            ]
            for member, relative in sorted(members, key=natural_key):
                if member.file_size > MAX_ARCHIVE_MEMBER_BYTES:
                    raise StorageError("Archive member exceeds the size limit.")
                # Store only the basename to prevent user-controlled directory
                # layouts from escaping the session boundary.
                destination = extracted_dir / relative.name
                if destination.name in used_names:
                    raise StorageError("Archive contains duplicate EDF filenames.")
                used_names.add(destination.name)
                with archive.open(member) as source, destination.open("wb") as output:
                    shutil.copyfileobj(source, output)
                outputs.append(destination)
            return outputs

    def deidentified_path(self, session_id: str, record_id: str) -> Path:
        """Return the private destination for a de-identified EDF.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        record_id : str
            Opaque recording identifier.

        Returns
        -------
        pathlib.Path
            Internal de-identified EDF path.
        """

        return self.directory(session_id, "deidentified") / f"{record_id}.edf"

    def processed_path(self, session_id: str, record_id: str) -> Path:
        """Return the private destination for a processed NPZ artifact.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        record_id : str
            Opaque recording identifier.

        Returns
        -------
        pathlib.Path
            Internal processed-artifact path.
        """

        return self.directory(session_id, "processed") / f"{record_id}.npz"

    def cleanup_session(self, session_id: str, *, keep_deidentified: bool = False) -> None:
        """Delete transient session files after processing, keeping only local preview data."""

        session_dir = self.root / session_id
        if not session_dir.exists():
            return
        if not keep_deidentified:
            shutil.rmtree(session_dir)
            return
        for name in ("original", "work", "extracted", "processed", "explanations"):
            shutil.rmtree(session_dir / name, ignore_errors=True)

    def delete_session(self, session_id: str) -> None:
        """Delete all private files belonging to one user-requested session.

        Parameters
        ----------
        session_id : str
            Opaque session identifier whose protected storage should be removed.
        """

        shutil.rmtree(self.root / session_id, ignore_errors=True)
