"""Safe session-scoped filesystem storage."""

from __future__ import annotations

import shutil
import re
import os
import secrets
import stat
import time
from datetime import datetime, timezone
import zipfile
from pathlib import Path, PurePosixPath

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from fastapi import UploadFile

from backend.app.core.config import (
    MAX_ARCHIVE_MEMBER_BYTES,
    MAX_EDF_FILES_PER_ARCHIVE,
    MAX_UPLOAD_BYTES,
    SESSION_STORAGE_DIR,
    STORAGE_KEY_ENV,
)
from backend.app.privacy.crypto import CryptoError, read_base64_key
from backend.app.research.chb_mit import sidecar_annotations, summary_annotations


class StorageError(ValueError):
    """Raised when an archive or storage operation is unsafe."""


_ENCRYPTED_MAGIC = b"MDS01GCM1"
_NONCE_BYTES = 12
_TAG_BYTES = 16
_MAX_ANNOTATION_MEMBER_BYTES = 1024 * 1024
MAX_ARCHIVE_TOTAL_BYTES = int(os.getenv("MDS01_MAX_ARCHIVE_TOTAL_BYTES", str(2 * 1024**3)))
MAX_ZIP_COMPRESSION_RATIO = float(os.getenv("MDS01_MAX_ZIP_COMPRESSION_RATIO", "100"))
MAX_ARCHIVE_MEMBER_COUNT = int(os.getenv("MDS01_MAX_ARCHIVE_MEMBER_COUNT", "4096"))
if MAX_ARCHIVE_TOTAL_BYTES <= 0 or MAX_ZIP_COMPRESSION_RATIO <= 0 or MAX_ARCHIVE_MEMBER_COUNT <= 0:
    raise RuntimeError("Archive limits must be positive.")


class SessionStorage:
    """Manage private files for opaque analysis sessions.

    The class owns the directory layout but never exposes private paths in
    API responses. All original and derived artifacts are transient by default.
    """

    def __init__(self, root: Path = SESSION_STORAGE_DIR, storage_key: bytes | None = None) -> None:
        """Configure storage beneath a session-root directory.

        Parameters
        ----------
        root : pathlib.Path
            Parent directory for all session files.
        """

        self.root = root
        self.storage_key = storage_key

    def session_dir(self, session_id: str) -> Path:
        """Create and return the private root for one session.

        Parameters
        ----------
        session_id : str
            Opaque session identifier generated by the application.

        Returns
        -------
        pathlib.Path
            Session directory path for internal service use.
        """

        safe_id = self._safe_session_id(session_id)
        root = self.root
        if root.is_symlink() or (root.exists() and not root.is_dir()):
            raise StorageError("Private storage root is invalid.")
        root.mkdir(parents=True, exist_ok=True)
        path = root / safe_id
        if path.is_symlink() or (path.exists() and not path.is_dir()):
            raise StorageError("Private session storage is invalid.")
        path.mkdir(parents=True, exist_ok=True)
        os.chmod(root, 0o700)
        os.chmod(path, 0o700)
        return path

    @staticmethod
    def _safe_token(value: str, prefix: str) -> str:
        """Validate one opaque storage token without accepting a path."""

        if not value.startswith(prefix) or Path(value).name != value:
            raise StorageError("Storage identifier is invalid.")
        return value

    @staticmethod
    def _safe_session_id(value: str) -> str:
        """Validate an EEG or video session directory identifier."""

        if Path(value).name != value or not value.startswith(("SES-", "VID-")):
            raise StorageError("Storage identifier is invalid.")
        return value

    def _drafts_root(self, *, create: bool) -> Path:
        """Return the draft root without following a symlink."""

        path = self.root / "_drafts"
        if path.is_symlink():
            raise StorageError("Staged upload storage is invalid.")
        if path.exists():
            metadata = path.lstat()
            if metadata.st_mode & 0o170000 != 0o040000:
                raise StorageError("Staged upload storage is invalid.")
        elif create:
            path.mkdir(parents=True, exist_ok=True)
        return path

    def draft_dir(self, draft_id: str) -> Path:
        """Create and return the private directory for one staged upload."""

        safe_id = self._safe_token(draft_id, "UPL-")
        path = self._drafts_root(create=True) / safe_id
        path.mkdir(parents=True, exist_ok=True)
        os.chmod(self.root, 0o700)
        os.chmod(path.parent, 0o700)
        os.chmod(path, 0o700)
        return path

    def draft_path(self, draft_id: str) -> Path:
        """Return the encrypted archive path for one staged upload."""

        return self.draft_dir(draft_id) / "upload.zip.enc"

    def draft_size(self, draft_id: str) -> int:
        """Return a staged ciphertext size without following symlinks."""

        safe_id = self._safe_token(draft_id, "UPL-")
        path = self._drafts_root(create=False) / safe_id / "upload.zip.enc"
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            return 0
        if not path.is_file() or metadata.st_mode & 0o170000 != 0o100000:
            raise StorageError("Staged upload storage is invalid.")
        return metadata.st_size

    def directory(self, session_id: str, name: str) -> Path:
        """Create and return one approved artifact directory.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        name : str
            One of ``original``, ``work``, ``extracted``, ``deidentified``,
            ``processed``, ``retained``, or ``explanations``.

        Returns
        -------
        pathlib.Path
            Private directory for the requested artifact category.

        Raises
        ------
        StorageError
            Raised for unknown artifact categories.
        """

        if name not in {"original", "work", "extracted", "deidentified", "processed", "retained", "explanations"}:
            raise StorageError("Unknown session storage area.")
        path = self.session_dir(session_id) / name
        if path.is_symlink() or (path.exists() and not path.is_dir()):
            raise StorageError("Session storage area is invalid.")
        path.mkdir(parents=True, exist_ok=True)
        os.chmod(path, 0o700)
        return path

    async def save_upload(
        self,
        session_id: str,
        upload: UploadFile,
        *,
        max_bytes: int = MAX_UPLOAD_BYTES,
        filename: str = "upload.zip.enc",
    ) -> Path:
        """Stream an uploaded ZIP to private original-file storage.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        upload : fastapi.UploadFile
            Multipart upload supplied by FastAPI.

        Returns
        -------
        pathlib.Path
            Internal path to the stored archive.

        Raises
        ------
        StorageError
            Raised for missing filenames or oversized uploads.
        """

        if not upload.filename:
            raise StorageError("Uploaded archive has no filename.")
        if Path(filename).name != filename or not filename:
            raise StorageError("Stored upload name is invalid.")
        destination = self.directory(session_id, "original") / filename
        return await self._encrypt_upload(upload, destination, max_bytes=max_bytes)

    async def save_draft_upload(self, draft_id: str, upload: UploadFile) -> Path:
        """Encrypt a ZIP into short-lived private draft storage."""

        return await self._encrypt_upload(upload, self.draft_path(draft_id), max_bytes=MAX_UPLOAD_BYTES)

    async def _encrypt_upload(self, upload: UploadFile, destination: Path, *, max_bytes: int) -> Path:
        """Stream one upload through AES-GCM into an owner-only file."""

        total = 0
        nonce = secrets.token_bytes(_NONCE_BYTES)
        encryptor = Cipher(algorithms.AES(self._key()), modes.GCM(nonce)).encryptor()
        try:
            with self._open_private_output(destination) as output:
                output.write(_ENCRYPTED_MAGIC)
                output.write(nonce)
                while chunk := await upload.read(1024 * 1024):
                    total += len(chunk)
                    if total > max_bytes:
                        raise StorageError("Uploaded archive exceeds the size limit.")
                    output.write(encryptor.update(chunk))
                output.write(encryptor.finalize())
                output.write(encryptor.tag)
        except Exception:
            destination.unlink(missing_ok=True)
            raise
        os.chmod(destination, 0o600)
        return destination

    def promote_draft(self, draft_id: str, session_id: str) -> Path:
        """Copy an encrypted draft into a session, retaining rollback safety."""

        source = self.draft_path(draft_id)
        if not source.exists():
            raise StorageError("Upload draft was not found.")
        destination = self.directory(session_id, "original") / "upload.zip.enc"
        try:
            with self._open_private_input(source) as input_stream, self._open_private_output(destination) as output_stream:
                shutil.copyfileobj(input_stream, output_stream)
        except FileExistsError as exc:
            raise StorageError("Session upload already exists.") from exc
        return destination

    def delete_draft(self, draft_id: str) -> None:
        """Delete one staged archive and its private directory."""

        safe_id = self._safe_token(draft_id, "UPL-")
        drafts_root = self._drafts_root(create=False)
        if drafts_root.exists():
            self._remove_tree(drafts_root / safe_id)

    def cleanup_orphaned_drafts(self, active_draft_ids: set[str], older_than: datetime) -> None:
        """Remove old draft directories that have no database row."""

        drafts_root = self._drafts_root(create=False)
        if not drafts_root.exists():
            return
        for candidate in drafts_root.iterdir():
            if candidate.name in active_draft_ids or not candidate.name.startswith("UPL-"):
                continue
            metadata = candidate.lstat()
            if metadata.st_mode & 0o170000 != 0o040000:
                raise StorageError("Staged upload storage is invalid.")
            modified_at = datetime.fromtimestamp(metadata.st_mtime, timezone.utc)
            if modified_at <= older_than:
                self._remove_tree(candidate)

    def _key(self) -> bytes:
        """Return the injected test key or the required runtime storage key."""

        try:
            return self.storage_key or read_base64_key(STORAGE_KEY_ENV)
        except CryptoError as exc:
            raise StorageError(str(exc)) from exc

    def materialize_archive(self, session_id: str, encrypted_path: Path, *, deadline: float | None = None) -> Path:
        """Decrypt one private ZIP into a short-lived, owner-only work path."""

        safe_path = self._validate_materialization_source(session_id, encrypted_path)
        destination = self.directory(session_id, "work") / "upload.zip"
        return self._materialize_encrypted(safe_path, destination, deadline=deadline)

    def materialize_retained_artifact(
        self, session_id: str, encrypted_path: Path, name: str, *, deadline: float | None = None
    ) -> Path:
        """Decrypt one retained artifact into temporary private work storage."""

        if Path(name).name != name or not name:
            raise StorageError("Retained artifact name is invalid.")
        safe_path = self._validate_materialization_source(session_id, encrypted_path)
        destination = self.directory(session_id, "work") / name
        return self._materialize_encrypted(safe_path, destination, deadline=deadline)

    def _validate_materialization_source(self, session_id: str, encrypted_path: Path) -> Path:
        """Require an existing regular ciphertext below one session root."""

        safe_id = self._safe_session_id(session_id)
        root = Path(os.path.abspath(self.root))
        if root.is_symlink() or not root.is_dir():
            raise StorageError("Private storage root is invalid.")
        session_root = root / safe_id
        candidate = Path(os.path.abspath(encrypted_path))
        try:
            relative = candidate.relative_to(session_root)
        except ValueError as exc:
            raise StorageError("Stored artifact path is outside its session.") from exc
        if session_root.is_symlink() or not session_root.is_dir():
            raise StorageError("Private session storage is invalid.")
        current = session_root
        for part in relative.parts[:-1]:
            current /= part
            if current.is_symlink() or not current.is_dir():
                raise StorageError("Stored artifact path is invalid.")
        try:
            metadata = candidate.lstat()
        except FileNotFoundError as exc:
            raise StorageError("Stored artifact was not found.") from exc
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise StorageError("Stored artifact path is invalid.")
        return candidate

    def _materialize_encrypted(
        self, encrypted_path: Path, destination: Path, *, deadline: float | None = None
    ) -> Path:
        """Decrypt one AES-GCM file and remove the plaintext on failure."""

        try:
            if destination.is_symlink() or (destination.exists() and not destination.is_file()):
                raise StorageError("Plaintext destination is invalid.")
            size = encrypted_path.stat().st_size
            minimum_size = len(_ENCRYPTED_MAGIC) + _NONCE_BYTES + _TAG_BYTES
            if size < minimum_size:
                raise StorageError("Stored archive is incomplete.")
            with encrypted_path.open("rb") as source:
                if source.read(len(_ENCRYPTED_MAGIC)) != _ENCRYPTED_MAGIC:
                    raise StorageError("Stored archive is not encrypted.")
                nonce = source.read(_NONCE_BYTES)
                source.seek(size - _TAG_BYTES)
                tag = source.read(_TAG_BYTES)
                source.seek(len(_ENCRYPTED_MAGIC) + _NONCE_BYTES)
                remaining = size - len(_ENCRYPTED_MAGIC) - _NONCE_BYTES - _TAG_BYTES
                decryptor = Cipher(algorithms.AES(self._key()), modes.GCM(nonce, tag)).decryptor()
                with self._open_private_output(destination) as output:
                    while remaining:
                        if deadline is not None and time.monotonic() > deadline:
                            raise StorageError("Stored artifact materialization timed out.")
                        chunk = source.read(min(1024 * 1024, remaining))
                        if not chunk:
                            raise StorageError("Stored archive is incomplete.")
                        remaining -= len(chunk)
                        output.write(decryptor.update(chunk))
                    output.write(decryptor.finalize())
            os.chmod(destination, 0o600)
            return destination
        except StorageError:
            self._remove_plaintext_file(destination)
            raise
        except Exception as exc:
            self._remove_plaintext_file(destination)
            raise StorageError("Stored archive cannot be decrypted.") from exc

    @staticmethod
    def _remove_plaintext_file(path: Path) -> None:
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            return
        if stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
            path.unlink(missing_ok=True)

    @staticmethod
    def _open_private_input(path: Path):
        """Open a regular private file without following a symlink."""

        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        return os.fdopen(os.open(path, flags), "rb")

    @staticmethod
    def _open_private_output(path: Path):
        """Create a new owner-only file without following a symlink."""

        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
        return os.fdopen(os.open(path, flags, 0o600), "wb")

    def store_encrypted_artifact(self, session_id: str, source_path: Path, name: str) -> Path:
        """Encrypt one retained derived artifact and return its private path.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        source_path : pathlib.Path
            Temporary plaintext artifact to encrypt and remove on success.
        name : str
            Safe artifact basename, without a user-controlled path.

        Returns
        -------
        pathlib.Path
            Private encrypted artifact path.

        Raises
        ------
        StorageError
            Raised when the source is invalid or encryption fails.
        """

        if Path(name).name != name or not name:
            raise StorageError("Retained artifact name is invalid.")
        destination = self.directory(session_id, "retained") / f"{name}.enc"
        nonce = secrets.token_bytes(_NONCE_BYTES)
        encryptor = Cipher(algorithms.AES(self._key()), modes.GCM(nonce)).encryptor()
        try:
            with self._open_private_input(Path(source_path)) as source, self._open_private_output(destination) as output:
                output.write(_ENCRYPTED_MAGIC)
                output.write(nonce)
                while chunk := source.read(1024 * 1024):
                    output.write(encryptor.update(chunk))
                output.write(encryptor.finalize())
                output.write(encryptor.tag)
            os.chmod(destination, 0o600)
            return destination
        except Exception as exc:
            destination.unlink(missing_ok=True)
            raise StorageError("Retained artifact could not be encrypted.") from exc
        finally:
            Path(source_path).unlink(missing_ok=True)

    @staticmethod
    def _safe_member_path(member_name: str) -> PurePosixPath:
        """Validate one ZIP member path against traversal attacks.

        Parameters
        ----------
        member_name : str
            Path supplied by the ZIP archive.

        Returns
        -------
        pathlib.PurePosixPath
            Normalized safe archive-relative path.

        Raises
        ------
        StorageError
            Raised for absolute paths, parent traversal, or invalid names.
        """

        member_name = member_name.replace("\\", "/")
        candidate = PurePosixPath(member_name)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise StorageError("Archive contains an unsafe path.")
        if not candidate.name:
            raise StorageError("Archive contains an invalid file path.")
        return candidate

    @staticmethod
    def _is_hidden_member(path: PurePosixPath) -> bool:
        """Return whether a ZIP member is hidden operating-system metadata."""

        return any(part == "__MACOSX" or part.startswith(".") for part in path.parts)

    @classmethod
    def _validated_archive_members(cls, archive: zipfile.ZipFile) -> list[zipfile.ZipInfo]:
        """Validate ZIP metadata before any member is read or extracted."""

        members = archive.infolist()
        if len(members) > MAX_ARCHIVE_MEMBER_COUNT:
            raise StorageError("ZIP archive contains too many members.")

        total_uncompressed = 0
        total_compressed = 0
        for member in members:
            mode = (member.external_attr >> 16) & 0o170000
            if mode in {stat.S_IFLNK, stat.S_IFCHR, stat.S_IFBLK, stat.S_IFIFO, stat.S_IFSOCK}:
                raise StorageError("Archive contains a special file.")
            if member.file_size < 0 or member.compress_size < 0:
                raise StorageError("Archive contains invalid size metadata.")
            if member.is_dir():
                continue
            if member.file_size > MAX_ARCHIVE_MEMBER_BYTES:
                raise StorageError("Archive member exceeds the size limit.")
            total_uncompressed += member.file_size
            total_compressed += member.compress_size
            if total_uncompressed > MAX_ARCHIVE_TOTAL_BYTES:
                raise StorageError("ZIP archive exceeds the cumulative total size limit.")
            if member.file_size / max(member.compress_size, 1) > MAX_ZIP_COMPRESSION_RATIO:
                raise StorageError("Archive member exceeds the safe compression ratio.")
        if total_compressed > MAX_UPLOAD_BYTES:
            raise StorageError("ZIP archive exceeds the compressed size limit.")
        return members

    def read_reference_annotations(self, archive_path: Path) -> dict[str, tuple[str, list[tuple[float, float]]]]:
        """Read optional CHB-MIT reference intervals without retaining source names."""

        annotations: dict[str, tuple[str, list[tuple[float, float]]]] = {}
        summaries: dict[str, list[tuple[float, float]]] = {}
        sidecars: dict[str, list[tuple[float, float]]] = {}
        with zipfile.ZipFile(archive_path) as archive:
            for member in self._validated_archive_members(archive):
                if member.is_dir():
                    continue
                relative = self._safe_member_path(member.filename)
                if self._is_hidden_member(relative) or member.file_size > _MAX_ANNOTATION_MEMBER_BYTES:
                    continue
                lower_name = relative.name.lower()
                try:
                    if lower_name.endswith("-summary.txt"):
                        text = archive.read(member).decode("utf-8-sig")
                        summaries.update(summary_annotations(text))
                    elif lower_name.endswith(".edf.seizures"):
                        edf_name = lower_name.removesuffix(".seizures")
                        sidecars[edf_name] = sidecar_annotations(archive.read(member))
                except (UnicodeDecodeError, ValueError):
                    continue

        for filename, intervals in sidecars.items():
            annotations[filename] = ("chb-mit-sidecar", intervals)
        for filename, intervals in summaries.items():
            annotations[filename] = ("chb-mit-summary", intervals)
        return annotations

    def extract_edfs(self, session_id: str, archive_path: Path) -> list[Path]:
        """Extract validated EDF members into the session directory.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        archive_path : pathlib.Path
            Private ZIP archive path.

        Returns
        -------
        list[pathlib.Path]
            Extracted EDF paths in natural filename order.

        Raises
        ------
        StorageError
            Raised for missing EDF files, unsafe paths, duplicate basenames,
            oversized members, or too many recordings.
        """

        extracted_dir = self.directory(session_id, "extracted")
        with zipfile.ZipFile(archive_path) as archive:
            members: list[tuple[zipfile.ZipInfo, PurePosixPath]] = []
            for member in self._validated_archive_members(archive):
                if member.is_dir():
                    continue
                relative = self._safe_member_path(member.filename)
                if self._is_hidden_member(relative) or relative.suffix.lower() != ".edf":
                    continue
                members.append((member, relative))
            if not members:
                raise StorageError("ZIP archive does not contain EDF files.")
            if len(members) > MAX_EDF_FILES_PER_ARCHIVE:
                raise StorageError("ZIP archive contains too many EDF files.")
            outputs: list[Path] = []
            used_names: set[str] = set()
            natural_key = lambda item: [
                int(part) if part.isdigit() else part.lower()
                for part in re.split(r"(\d+)", item[1].name)
            ]
            for member, relative in sorted(members, key=natural_key):
                # Store only the basename to prevent user-controlled directory
                # layouts from escaping the session boundary.
                destination = extracted_dir / relative.name
                if destination.name in used_names:
                    raise StorageError("Archive contains duplicate EDF filenames.")
                used_names.add(destination.name)
                with archive.open(member) as source, destination.open("wb") as output:
                    shutil.copyfileobj(source, output)
                os.chmod(destination, 0o600)
                outputs.append(destination)
            return outputs

    def cleanup_session(self, session_id: str, *, keep_retained: bool = False) -> None:
        """Delete transient session files after processing.

        Parameters
        ----------
        session_id : str
            Opaque session identifier.
        keep_retained : bool
            Preserve encrypted model-positive artifacts when true.
        """

        session_dir = self.root / self._safe_session_id(session_id)
        if not keep_retained:
            self._remove_tree(session_dir)
            return
        for name in ("original", "work", "extracted", "deidentified", "processed", "explanations"):
            self._remove_tree(session_dir / name)

    @staticmethod
    def _remove_tree(path: Path) -> None:
        """Remove a private directory and fail closed if deletion fails."""

        if not path.exists():
            if path.is_symlink():
                raise StorageError("Private storage cleanup encountered a symlink.")
            return
        try:
            shutil.rmtree(path)
        except OSError as exc:
            raise StorageError("Private storage cleanup failed.") from exc
        if path.exists():
            raise StorageError("Private storage cleanup could not be verified.")

    def delete_retained_artifact(self, path: Path) -> None:
        """Delete one encrypted retained artifact after a recording failure.

        Parameters
        ----------
        path : pathlib.Path
            Internal retained-artifact path created by this storage service.

        Raises
        ------
        StorageError
            Raised when the path is outside this storage service's retained
            directories.
        """

        retained_root = self.root.resolve()
        candidate = path.resolve()
        if retained_root not in candidate.parents or candidate.parent.name != "retained":
            raise StorageError("Retained artifact path is invalid.")
        candidate.unlink(missing_ok=True)

    def delete_session(self, session_id: str) -> None:
        """Delete all private files belonging to one user-requested session.

        Parameters
        ----------
        session_id : str
            Opaque session identifier whose protected storage should be removed.
        """

        self._remove_tree(self.root / self._safe_session_id(session_id))

    def cleanup_expired_drafts(self, draft_ids: list[str]) -> None:
        """Remove expired staged upload directories."""

        for draft_id in draft_ids:
            self.delete_draft(draft_id)
